import type { Study } from '@/components/ui/StudyCard';

export const popularStudiesData: Study[] = [
  {
    id: 1,
    status: '모집중',
    title: 'Figma 스터디하실 분 모집합니다!',
    tags: ['디자인', '온라인/오프라인', '체계적인'],
    author: '민서송이',
    likeCount: 12,
  },
  {
    id: 2,
    status: '모집중',
    title: 'React 실력 키우실 분! 초보도 환영!',
    tags: ['코딩', '온라인', '자유로운'],
    author: '코딩왕',
    likeCount: 25,
  },
  {
    id: 3,
    status: '모집완료',
    title: '토익 900점 목표로 같이 공부하실 분 모집합니다.',
    tags: ['어학', '오프라인', '체계적인'],
    author: '영어고수',
    likeCount: 8,
  },
  {
    id: 4,
    status: '모집중',
    title: 'CS 스터디 취준생 모여라',
    tags: ['코딩', '오프라인', '자유로운'],
    author: '컴공눈송',
    likeCount: 30,
  },
  {
    id: 5,
    status: '모집중',
    title: 'UX/UI 포트폴리오 만들 디자이너 구함',
    tags: ['디자인', '오프라인', '협력적인'],
    author: '디자인장인',
    likeCount: 18,
  },
  {
    id: 6,
    status: '모집중',
    title: '알고리즘 문제풀이 코테 박살내기',
    tags: ['코딩', '온라인', '체계적인'],
    author: '코딩천재',
    likeCount: 40,
  },
  {
    id: 7,
    status: '모집완료',
    title: '사이드 플젝 하실 분 기획자/코딩자',
    tags: ['코딩', '온라인', '자유로운'],
    author: 'PM지망생',
    likeCount: 22,
  },
  {
    id: 8,
    status: '모집중',
    title: '영어 회화 스터디 주 2회 진행',
    tags: ['어학', '오프라인', '체계적인'],
    author: '유학생',
    likeCount: 15,
  },
];
