import type { MyStudyLog } from './component/MyStudyLogCard';

export const myStudyLogListData: MyStudyLog[] = [
  {
    id: 1,
    title: '자료구조 복습 일지',
    role: '스터디원',
    writerNickname: '리더송이',
    viewCount: 42,
    content:
      '스택과 큐 기본 개념을 다시 정리하고, 직접 구현해 보았어요. 배열 기반과 링크드 리스트 기반 차이도 비교했습니다.',
    link: 'https://example.com/자료구조-정리',
    attachments: [
      {
        id: 1,
        name: '자료구조_정리.pdf',
        type: 'pdf',
        url: '/mock/files/자료구조_정리.pdf',
      },
    ],
    likeCount: 3,
    heartCount: 5,
    laughCount: 0,
    surpriseCount: 1,
    questionCount: 0,
  },
  {
    id: 2,
    title: '알고리즘 문제 풀이',
    role: '스터디원',
    writerNickname: '코딩송',
    viewCount: 31,
    content: '백준 DP 기본 문제 3개를 풀었고, 점화식 세우는 과정을 상세히 적어두었습니다.',
    link: 'https://www.acmicpc.net/',
    attachments: [
      {
        id: 1,
        name: 'dp_풀이노트.png',
        type: 'png',
        url: '/mock/files/dp_풀이노트.png',
      },
    ],
    likeCount: 2,
    heartCount: 3,
    laughCount: 1,
    surpriseCount: 0,
    questionCount: 1,
  },
  {
    id: 3,
    title: 'React 훅 정리',
    role: '스터디원',
    writerNickname: '프론트송',
    viewCount: 55,
    content: 'useState, useEffect, useMemo 위주로 실습했고, 커스텀 훅 예제도 하나 만들어봤어요.',
    link: 'https://react.dev/reference/react',
    attachments: [
      {
        id: 1,
        name: 'react_hooks_정리.pdf',
        type: 'pdf',
        url: '/mock/files/react_hooks_정리.pdf',
      },
    ],
    likeCount: 6,
    heartCount: 4,
    laughCount: 0,
    surpriseCount: 2,
    questionCount: 2,
  },
  {
    id: 4,
    title: '네트워크 계층 정리',
    role: '스터디원',
    writerNickname: '네트워크송',
    viewCount: 27,
    content: 'OSI 7계층과 TCP/IP 4계층을 비교하면서 각 계층의 역할을 정리했습니다.',
    link: undefined,
    attachments: [
      {
        id: 1,
        name: 'network_layer.png',
        type: 'png',
        url: '/mock/files/network_layer.png',
      },
    ],
    likeCount: 1,
    heartCount: 2,
    laughCount: 0,
    surpriseCount: 1,
    questionCount: 3,
  },
  {
    id: 5,
    title: 'SQL 조인 연습',
    role: '스터디원',
    writerNickname: '데이터송',
    viewCount: 36,
    content: 'INNER JOIN, LEFT JOIN, RIGHT JOIN 차이를 예시 테이블로 설명했습니다.',
    link: 'https://sqlbolt.com/',
    attachments: [],
    likeCount: 2,
    heartCount: 1,
    laughCount: 0,
    surpriseCount: 0,
    questionCount: 2,
  },
  {
    id: 6,
    title: '머신러닝 파이프라인',
    role: '스터디원',
    writerNickname: 'AI송',
    viewCount: 48,
    content:
      '데이터 전처리 → 학습 → 검증 → 테스트 전체 파이프라인을 sklearn으로 구성해 보았습니다.',
    link: undefined,
    attachments: [
      {
        id: 1,
        name: 'ml_pipeline.pdf',
        type: 'pdf',
        url: '/mock/files/ml_pipeline.pdf',
      },
    ],
    likeCount: 5,
    heartCount: 3,
    laughCount: 1,
    surpriseCount: 1,
    questionCount: 1,
  },
  {
    id: 7,
    title: 'HTTP와 REST API',
    role: '스터디원',
    writerNickname: '백엔드송',
    viewCount: 22,
    content: 'HTTP 메서드와 REST API 설계 규칙을 정리하고, 간단한 엔드포인트 설계를 해봤습니다.',
    link: 'https://example.com/rest-api',
    attachments: [],
    likeCount: 1,
    heartCount: 2,
    laughCount: 0,
    surpriseCount: 0,
    questionCount: 1,
  },
  {
    id: 8,
    title: 'CS 면접 대비 노트',
    role: '스터디원',
    writerNickname: '면접송',
    viewCount: 60,
    content: '프로세스/스레드, 동기/비동기, 뮤텍스/세마포어 개념을 정리했습니다.',
    link: undefined,
    attachments: [
      {
        id: 1,
        name: 'cs_interview.pdf',
        type: 'pdf',
        url: '/mock/files/cs_interview.pdf',
      },
      {
        id: 2,
        name: 'cs_diagram.png',
        type: 'png',
        url: '/mock/files/cs_diagram.png',
      },
    ],
    likeCount: 7,
    heartCount: 6,
    laughCount: 0,
    surpriseCount: 2,
    questionCount: 4,
  },
];
