import type { Study } from '@/components/ui/StudyCard';

export const matchStudiesData: Study[] = [
  {
    id: 17,
    status: '모집중',
    title: 'Figma 스터디하실 분 모집합니다!',
    tags: ['디자인', '온라인/오프라인', '체계적인'],
    author: '민서송이',
    likeCount: 12,
  },
  {
    id: 8,
    status: '모집중',
    title: 'React 실력 키우실 분! 초보도 환영!',
    tags: ['개발', '온라인', '자율적인'],
    author: '개발왕',
    likeCount: 25,
  },
  {
    id: 25,
    status: '모집완료',
    title: '토익 900점 목표로 같이 공부하실 분 모집합니다.',
    tags: ['어학', '오프라인', '체계적인'],
    author: '영어고수',
    likeCount: 8,
  },
  {
    id: 5,
    status: '모집중',
    title: 'CS 스터디 취준생 모여라',
    tags: ['개발', '온라인', '자율적인'],
    author: '컴공눈송',
    likeCount: 30,
  },
  {
    id: 13,
    status: '모집중',
    title: 'UX/UI 포트폴리오 만들 디자이너 구함',
    tags: ['디자인', '오프라인', '체계적인'],
    author: '디자인장인',
    likeCount: 18,
  },
  {
    id: 2,
    status: '모집중',
    title: '알고리즘 문제풀이 코테 박살내기',
    tags: ['개발', '온라인', '자율적인'],
    author: '코딩천재',
    likeCount: 40,
  },
  {
    id: 30,
    status: '모집완료',
    title: '사이드 플젝 하실 분 기획자/개발자',
    tags: ['개발', '온라인', '자율적인'],
    author: 'PM지망생',
    likeCount: 22,
  },
  {
    id: 9,
    status: '모집중',
    title: '영어 회화 스터디 주 2회 진행',
    tags: ['어학', '오프라인', '체계적인'],
    author: '유학생',
    likeCount: 15,
  },
  {
    id: 19,
    status: '모집중',
    title: '프론트엔드 면접 대비 스터디',
    tags: ['개발', '온라인', '체계적인'],
    author: '면접러버',
    likeCount: 27,
  },
  {
    id: 4,
    status: '모집중',
    title: '서비스 기획 포트폴리오 스터디',
    tags: ['기획', '온라인', '자율적인'],
    author: '기획하는고양이',
    likeCount: 13,
  },
  {
    id: 21,
    status: '모집완료',
    title: 'JLPT N2 대비 일본어 스터디',
    tags: ['어학', '온라인', '체계적인'],
    author: '일본어장인',
    likeCount: 9,
  },
  {
    id: 14,
    status: '모집중',
    title: 'AWS 자격증 준비 스터디 (CLF)',
    tags: ['개발', '온라인', '체계적인'],
    author: '클라우드초보',
    likeCount: 19,
  },
  {
    id: 7,
    status: '모집중',
    title: '데이터 분석 입문 스터디 (Python/Pandas)',
    tags: ['데이터', '온라인', '자율적인'],
    author: '데분초보',
    likeCount: 24,
  },
  {
    id: 23,
    status: '모집중',
    title: '독서 스터디: 인문학으로 생각 확장하기',
    tags: ['독서', '오프라인', '자율적인'],
    author: '책덕후',
    likeCount: 16,
  },
  {
    id: 6,
    status: '모집중',
    title: 'GitHub 협업 플젝 같이 해봐요',
    tags: ['개발', '온라인', '자율적인'],
    author: '깃초보',
    likeCount: 20,
  },
  {
    id: 1,
    status: '모집완료',
    title: '영상 편집 프리미어 프로 스터디',
    tags: ['디자인', '오프라인', '체계적인'],
    author: '비디오편집자',
    likeCount: 10,
  },
  {
    id: 11,
    status: '모집중',
    title: 'AI 윤리와 미래 기술 독서모임',
    tags: ['인공지능', '온라인', '자율적인'],
    author: '철학하는개발자',
    likeCount: 14,
  },
  {
    id: 28,
    status: '모집중',
    title: 'Spring Boot 심화 스터디',
    tags: ['개발', '온라인', '체계적인'],
    author: '백엔드러버',
    likeCount: 31,
  },
  {
    id: 3,
    status: '모집중',
    title: '포토샵 실무 감각 키우기 스터디',
    tags: ['디자인', '오프라인', '자율적인'],
    author: '그래픽고수',
    likeCount: 17,
  },
  {
    id: 10,
    status: '모집완료',
    title: '취업자 모의면접 스터디 (비대면)',
    tags: ['취업', '온라인', '체계적인'],
    author: 'HR마스터',
    likeCount: 23,
  },
  {
    id: 20,
    status: '모집중',
    title: 'Node.js & Express 프로젝트 만들기',
    tags: ['개발', '온라인', '자율적인'],
    author: '노드러버',
    likeCount: 28,
  },
  {
    id: 22,
    status: '모집중',
    title: '포트폴리오 피드백 스터디 (디자인)',
    tags: ['디자인', '온라인', '체계적인'],
    author: 'UI연구소',
    likeCount: 19,
  },
  {
    id: 15,
    status: '모집중',
    title: '면접 영어 회화 집중 훈련',
    tags: ['어학', '온라인', '체계적인'],
    author: '취준유학생',
    likeCount: 21,
  },
  {
    id: 12,
    status: '모집완료',
    title: 'MBA 입시 스터디: 경영학 개론부터',
    tags: ['경영', '온라인', '체계적인'],
    author: '비즈니스러버',
    likeCount: 7,
  },
  {
    id: 16,
    status: '모집중',
    title: '책 한 권으로 끝내는 머신러닝 기초',
    tags: ['데이터', '온라인', '자율적인'],
    author: 'AI초보',
    likeCount: 33,
  },
  {
    id: 26,
    status: '모집중',
    title: '사회초년생을 위한 재테크 공부모임',
    tags: ['경제', '오프라인', '자율적인'],
    author: '통장요정',
    likeCount: 29,
  },
  {
    id: 24,
    status: '모집완료',
    title: '디지털 마케팅 실전 케이스 분석',
    tags: ['마케팅', '온라인', '체계적인'],
    author: '광고쟁이',
    likeCount: 11,
  },
  {
    id: 27,
    status: '모집중',
    title: 'Django 웹 개발 스터디',
    tags: ['개발', '온라인', '자율적인'],
    author: '파이썬소년',
    likeCount: 26,
  },
  {
    id: 18,
    status: '모집중',
    title: '취준생 자소서 첨삭 스터디',
    tags: ['취업', '온라인', '체계적인'],
    author: '이력서장인',
    likeCount: 18,
  },
  {
    id: 29,
    status: '모집중',
    title: '노션으로 일정관리/스터디 운영하기',
    tags: ['생산성', '온라인', '자율적인'],
    author: '노션마스터',
    likeCount: 12,
  },
];
